spring:
  application:
    name: FireShare

  security:
    user:
      name: "Hrishank"
      password: "Hrish@2006"

  datasource:
    url: jdbc:postgresql://localhost:5432/FireShare
    username: postgres
    password: 160406
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true